apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wordpress-sc
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-08a209249ddc08360
  accessPointId: fsap-01788d4f5a3710713
  directoryPerms: "0777"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/wordpress"

