apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000

